language: python
# OS: Linux
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    # OS: Windows
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH

# command to install dependencies
install:
  - pip install codecov
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - coverage run --source cprior -m pytest tests/

after_success:
  - codecov